import Head from 'next/head';
import Card from '/components/card/card.js';
import Nav from '/components/nav/nav.js';


export default function Home() {
  const wordDays = 5;

  return (
    <>
      <Head>
        <title>Brocabulary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <h1>Today's Brocabulary Word:</h1>

        {[...Array(wordDays)].map((item, i) =>
          <Card date={getDate({ daysBehind: i })} key={i} />
        )}

      </main>
    </>
  );
}

// TODO: Server-side render this data
function getDate({ daysBehind }) {
  const date = new Date();
  const PrevDateTime = date.setDate(date.getDate() - daysBehind);
  return new Date(PrevDateTime).toLocaleDateString();
}
